[project]
name = "webcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "contributory", email = "bosuutap@alwaysdata.net" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=3.4.7",
    "requests>=2.34.2",
    "uvicorn>=0.52.4",
]

[project.scripts]
webcode = "webcode:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
